### ISSUE TITLE
Plasma Wallet SDK

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#18]
## Description

Wallet features

- private key
- show balance
- tx and proof storage

We wanna use MetaMask.

**Comment by syuhei176** [comment]
If we use Metamask, we can use `eth_signTypedData`.

https://github.com/MetaMask/metamask-extension/issues/4752
https://github.com/MetaMask/eth-sig-util

**Comment by shogochiai** [comment]
Regarding UX

# if RPC is directed to the Childchain
- User must register host and port on Metamask
- Correct Balance on Metamask
- Gas estimation and gas price is just matched with displayed network

# if RPC is directed to the Rootchain
- User don"t need to register RPC info
- Metamask Balance would just display Rootchain balance. (We need to render the Childchain balance on Dapp's UI, rather than Metamask)
- How the Gas estimation and Gas price information on Metamask at the Tx submission UI of Metamask? Ideally we don't want to show the Metamask popup, and just wanna get signature from Metamask, and make Tx submision UI as dapps UI component.

**Comment by shogochiai** [comment]
@syuhei176 

proof storage and online-ness

Same discussion
https://github.com/cryptoeconomicslab/plasma-chamber/issues/35#issuecomment-430834608

**Comment by shogochiai** [comment]
done when we did demo
