### ISSUE TITLE
[out of dated]Fragmentation in deposit

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#80]
## Description

For the ease of handling of coins, we need fragmentation in the deposit.
We have to store much amount of history for that.
Users wanna swap their coins to reduce history.

**Comment by shogochiai** [comment]
"Fragment Sweeper" role solves it and this is for op.

## rough sketch
1. Op scan the tiny segment in a chunk
2. Op must be able to exit it even if it is not his segment
3. Challenge from segmentHolder must not be accepted when the last remainimg segment's value is less than 1/20 of chunk value. Otherwise it must be challengeable.
4. The exit will be funded as fast withdrawal by op because he knows the exit is safe.
5. Sweep compensation must be added for both op and segmentHolder

## ambiguity
- What if 1/20 size of different owners' segments scattered in a chunk?
- How is the compensation funded? Tx fee?
- Maybe this interactive game isn't harm safety. If this game goes wrong, deposit won't work anymore eventually.
